<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="LAPTOP-A0JC31GU" name="com.qait.hris.hrislogintest.MyTest" tests="6" failures="0" timestamp="27 Jun 2018 17:09:17 GMT" time="8.377" errors="1">
  <testcase name="loginUsingInvalidCredentials" time="0.000" classname="com.qait.hris.hrislogintest.MyTest">
    <skipped/>
  </testcase> <!-- loginUsingInvalidCredentials -->
  <testcase name="launchBrowser" time="8.377" classname="com.qait.hris.hrislogintest.MyTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qait.hris.hrislogin.PageVerification.openbrowser(PageVerification.java:14)
	at com.qait.hris.hrislogintest.MyTest.launchBrowser(MyTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- launchBrowser -->
  <testcase name="loginUsingBlankCredentials" time="0.000" classname="com.qait.hris.hrislogintest.MyTest">
    <skipped/>
  </testcase> <!-- loginUsingBlankCredentials -->
  <testcase name="loginUsingCorrectUsername" time="0.000" classname="com.qait.hris.hrislogintest.MyTest">
    <skipped/>
  </testcase> <!-- loginUsingCorrectUsername -->
  <testcase name="loginUsingInvalidPassword" time="0.000" classname="com.qait.hris.hrislogintest.MyTest">
    <skipped/>
  </testcase> <!-- loginUsingInvalidPassword -->
  <testcase name="loginUsingCorrectCredentials" time="0.000" classname="com.qait.hris.hrislogintest.MyTest">
    <skipped/>
  </testcase> <!-- loginUsingCorrectCredentials -->
</testsuite> <!-- com.qait.hris.hrislogintest.MyTest -->
